
: Bug Report
description: Report something that is not working correctly
title: "[Bug] "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Description
      description: Clearly describe the problem.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behaviour
      description: What actually happened.
    validations:
      required: true
      
